// Generated by view binder compiler. Do not edit!
package com.group213.gymder.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.SearchView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.widget.Toolbar;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.group213.gymder.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class FragmentSearchBinding implements ViewBinding {
  @NonNull
  private final FrameLayout rootView;

  @NonNull
  public final SearchView filterUsers;

  @NonNull
  public final Toolbar searchBar;

  @NonNull
  public final RecyclerView searchUsersRecycler;

  private FragmentSearchBinding(@NonNull FrameLayout rootView, @NonNull SearchView filterUsers,
      @NonNull Toolbar searchBar, @NonNull RecyclerView searchUsersRecycler) {
    this.rootView = rootView;
    this.filterUsers = filterUsers;
    this.searchBar = searchBar;
    this.searchUsersRecycler = searchUsersRecycler;
  }

  @Override
  @NonNull
  public FrameLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static FragmentSearchBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static FragmentSearchBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.fragment_search, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static FragmentSearchBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.filterUsers;
      SearchView filterUsers = ViewBindings.findChildViewById(rootView, id);
      if (filterUsers == null) {
        break missingId;
      }

      id = R.id.searchBar;
      Toolbar searchBar = ViewBindings.findChildViewById(rootView, id);
      if (searchBar == null) {
        break missingId;
      }

      id = R.id.searchUsersRecycler;
      RecyclerView searchUsersRecycler = ViewBindings.findChildViewById(rootView, id);
      if (searchUsersRecycler == null) {
        break missingId;
      }

      return new FragmentSearchBinding((FrameLayout) rootView, filterUsers, searchBar,
          searchUsersRecycler);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
