// Generated by view binder compiler. Do not edit!
package com.group213.gymder.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.FrameLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.widget.Toolbar;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.group213.gymder.R;
import de.hdodenhof.circleimageview.CircleImageView;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class FragmentProfileBinding implements ViewBinding {
  @NonNull
  private final FrameLayout rootView;

  @NonNull
  public final View divider4;

  @NonNull
  public final TextView profileAge;

  @NonNull
  public final Button profileDelete;

  @NonNull
  public final Button profileEdit;

  @NonNull
  public final TextView profileInterests;

  @NonNull
  public final ConstraintLayout profileLayout;

  @NonNull
  public final Button profileLogout;

  @NonNull
  public final TextView profileName;

  @NonNull
  public final CircleImageView profilePFP;

  @NonNull
  public final Toolbar profileToolbar;

  @NonNull
  public final TextView profileUsername;

  private FragmentProfileBinding(@NonNull FrameLayout rootView, @NonNull View divider4,
      @NonNull TextView profileAge, @NonNull Button profileDelete, @NonNull Button profileEdit,
      @NonNull TextView profileInterests, @NonNull ConstraintLayout profileLayout,
      @NonNull Button profileLogout, @NonNull TextView profileName,
      @NonNull CircleImageView profilePFP, @NonNull Toolbar profileToolbar,
      @NonNull TextView profileUsername) {
    this.rootView = rootView;
    this.divider4 = divider4;
    this.profileAge = profileAge;
    this.profileDelete = profileDelete;
    this.profileEdit = profileEdit;
    this.profileInterests = profileInterests;
    this.profileLayout = profileLayout;
    this.profileLogout = profileLogout;
    this.profileName = profileName;
    this.profilePFP = profilePFP;
    this.profileToolbar = profileToolbar;
    this.profileUsername = profileUsername;
  }

  @Override
  @NonNull
  public FrameLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static FragmentProfileBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static FragmentProfileBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.fragment_profile, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static FragmentProfileBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.divider4;
      View divider4 = ViewBindings.findChildViewById(rootView, id);
      if (divider4 == null) {
        break missingId;
      }

      id = R.id.profileAge;
      TextView profileAge = ViewBindings.findChildViewById(rootView, id);
      if (profileAge == null) {
        break missingId;
      }

      id = R.id.profileDelete;
      Button profileDelete = ViewBindings.findChildViewById(rootView, id);
      if (profileDelete == null) {
        break missingId;
      }

      id = R.id.profileEdit;
      Button profileEdit = ViewBindings.findChildViewById(rootView, id);
      if (profileEdit == null) {
        break missingId;
      }

      id = R.id.profileInterests;
      TextView profileInterests = ViewBindings.findChildViewById(rootView, id);
      if (profileInterests == null) {
        break missingId;
      }

      id = R.id.profileLayout;
      ConstraintLayout profileLayout = ViewBindings.findChildViewById(rootView, id);
      if (profileLayout == null) {
        break missingId;
      }

      id = R.id.profileLogout;
      Button profileLogout = ViewBindings.findChildViewById(rootView, id);
      if (profileLogout == null) {
        break missingId;
      }

      id = R.id.profileName;
      TextView profileName = ViewBindings.findChildViewById(rootView, id);
      if (profileName == null) {
        break missingId;
      }

      id = R.id.profilePFP;
      CircleImageView profilePFP = ViewBindings.findChildViewById(rootView, id);
      if (profilePFP == null) {
        break missingId;
      }

      id = R.id.profileToolbar;
      Toolbar profileToolbar = ViewBindings.findChildViewById(rootView, id);
      if (profileToolbar == null) {
        break missingId;
      }

      id = R.id.profileUsername;
      TextView profileUsername = ViewBindings.findChildViewById(rootView, id);
      if (profileUsername == null) {
        break missingId;
      }

      return new FragmentProfileBinding((FrameLayout) rootView, divider4, profileAge, profileDelete,
          profileEdit, profileInterests, profileLayout, profileLogout, profileName, profilePFP,
          profileToolbar, profileUsername);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
