// Generated by view binder compiler. Do not edit!
package com.group213.gymder.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.group213.gymder.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class RegisterBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final EditText addressRegister;

  @NonNull
  public final EditText ageRegister;

  @NonNull
  public final EditText confirmRegister;

  @NonNull
  public final EditText emailRegister;

  @NonNull
  public final EditText genderRegister;

  @NonNull
  public final EditText interestsRegister;

  @NonNull
  public final EditText nameRegister;

  @NonNull
  public final EditText passwordRegister;

  @NonNull
  public final Button register2;

  @NonNull
  public final EditText usernameRegister;

  private RegisterBinding(@NonNull ConstraintLayout rootView, @NonNull EditText addressRegister,
      @NonNull EditText ageRegister, @NonNull EditText confirmRegister,
      @NonNull EditText emailRegister, @NonNull EditText genderRegister,
      @NonNull EditText interestsRegister, @NonNull EditText nameRegister,
      @NonNull EditText passwordRegister, @NonNull Button register2,
      @NonNull EditText usernameRegister) {
    this.rootView = rootView;
    this.addressRegister = addressRegister;
    this.ageRegister = ageRegister;
    this.confirmRegister = confirmRegister;
    this.emailRegister = emailRegister;
    this.genderRegister = genderRegister;
    this.interestsRegister = interestsRegister;
    this.nameRegister = nameRegister;
    this.passwordRegister = passwordRegister;
    this.register2 = register2;
    this.usernameRegister = usernameRegister;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static RegisterBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static RegisterBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.register, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static RegisterBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.address_register;
      EditText addressRegister = ViewBindings.findChildViewById(rootView, id);
      if (addressRegister == null) {
        break missingId;
      }

      id = R.id.age_register;
      EditText ageRegister = ViewBindings.findChildViewById(rootView, id);
      if (ageRegister == null) {
        break missingId;
      }

      id = R.id.confirm_register;
      EditText confirmRegister = ViewBindings.findChildViewById(rootView, id);
      if (confirmRegister == null) {
        break missingId;
      }

      id = R.id.email_register;
      EditText emailRegister = ViewBindings.findChildViewById(rootView, id);
      if (emailRegister == null) {
        break missingId;
      }

      id = R.id.gender_register;
      EditText genderRegister = ViewBindings.findChildViewById(rootView, id);
      if (genderRegister == null) {
        break missingId;
      }

      id = R.id.interests_register;
      EditText interestsRegister = ViewBindings.findChildViewById(rootView, id);
      if (interestsRegister == null) {
        break missingId;
      }

      id = R.id.name_register;
      EditText nameRegister = ViewBindings.findChildViewById(rootView, id);
      if (nameRegister == null) {
        break missingId;
      }

      id = R.id.password_register;
      EditText passwordRegister = ViewBindings.findChildViewById(rootView, id);
      if (passwordRegister == null) {
        break missingId;
      }

      id = R.id.register2;
      Button register2 = ViewBindings.findChildViewById(rootView, id);
      if (register2 == null) {
        break missingId;
      }

      id = R.id.username_register;
      EditText usernameRegister = ViewBindings.findChildViewById(rootView, id);
      if (usernameRegister == null) {
        break missingId;
      }

      return new RegisterBinding((ConstraintLayout) rootView, addressRegister, ageRegister,
          confirmRegister, emailRegister, genderRegister, interestsRegister, nameRegister,
          passwordRegister, register2, usernameRegister);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
