// Generated by view binder compiler. Do not edit!
package com.group213.gymder.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.group213.gymder.R;
import de.hdodenhof.circleimageview.CircleImageView;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class SearchItemBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final View divider;

  @NonNull
  public final TextView searchName;

  @NonNull
  public final CircleImageView searchPFP;

  @NonNull
  public final TextView searchUsername;

  private SearchItemBinding(@NonNull ConstraintLayout rootView, @NonNull View divider,
      @NonNull TextView searchName, @NonNull CircleImageView searchPFP,
      @NonNull TextView searchUsername) {
    this.rootView = rootView;
    this.divider = divider;
    this.searchName = searchName;
    this.searchPFP = searchPFP;
    this.searchUsername = searchUsername;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static SearchItemBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static SearchItemBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.search_item, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static SearchItemBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.divider;
      View divider = ViewBindings.findChildViewById(rootView, id);
      if (divider == null) {
        break missingId;
      }

      id = R.id.searchName;
      TextView searchName = ViewBindings.findChildViewById(rootView, id);
      if (searchName == null) {
        break missingId;
      }

      id = R.id.searchPFP;
      CircleImageView searchPFP = ViewBindings.findChildViewById(rootView, id);
      if (searchPFP == null) {
        break missingId;
      }

      id = R.id.searchUsername;
      TextView searchUsername = ViewBindings.findChildViewById(rootView, id);
      if (searchUsername == null) {
        break missingId;
      }

      return new SearchItemBinding((ConstraintLayout) rootView, divider, searchName, searchPFP,
          searchUsername);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
