// Generated by view binder compiler. Do not edit!
package com.group213.gymder.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageButton;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.widget.Toolbar;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.group213.gymder.R;
import de.hdodenhof.circleimageview.CircleImageView;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class SearchedUserBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final ImageButton dislike;

  @NonNull
  public final View divider2;

  @NonNull
  public final View divider3;

  @NonNull
  public final TextView interests;

  @NonNull
  public final ImageButton like;

  @NonNull
  public final TextView searchedAge;

  @NonNull
  public final TextView searchedName;

  @NonNull
  public final CircleImageView searchedUserPFP;

  @NonNull
  public final TextView searchedUsername;

  @NonNull
  public final Toolbar userToolbar;

  private SearchedUserBinding(@NonNull ConstraintLayout rootView, @NonNull ImageButton dislike,
      @NonNull View divider2, @NonNull View divider3, @NonNull TextView interests,
      @NonNull ImageButton like, @NonNull TextView searchedAge, @NonNull TextView searchedName,
      @NonNull CircleImageView searchedUserPFP, @NonNull TextView searchedUsername,
      @NonNull Toolbar userToolbar) {
    this.rootView = rootView;
    this.dislike = dislike;
    this.divider2 = divider2;
    this.divider3 = divider3;
    this.interests = interests;
    this.like = like;
    this.searchedAge = searchedAge;
    this.searchedName = searchedName;
    this.searchedUserPFP = searchedUserPFP;
    this.searchedUsername = searchedUsername;
    this.userToolbar = userToolbar;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static SearchedUserBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static SearchedUserBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.searched_user, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static SearchedUserBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.dislike;
      ImageButton dislike = ViewBindings.findChildViewById(rootView, id);
      if (dislike == null) {
        break missingId;
      }

      id = R.id.divider2;
      View divider2 = ViewBindings.findChildViewById(rootView, id);
      if (divider2 == null) {
        break missingId;
      }

      id = R.id.divider3;
      View divider3 = ViewBindings.findChildViewById(rootView, id);
      if (divider3 == null) {
        break missingId;
      }

      id = R.id.interests;
      TextView interests = ViewBindings.findChildViewById(rootView, id);
      if (interests == null) {
        break missingId;
      }

      id = R.id.like;
      ImageButton like = ViewBindings.findChildViewById(rootView, id);
      if (like == null) {
        break missingId;
      }

      id = R.id.searchedAge;
      TextView searchedAge = ViewBindings.findChildViewById(rootView, id);
      if (searchedAge == null) {
        break missingId;
      }

      id = R.id.searchedName;
      TextView searchedName = ViewBindings.findChildViewById(rootView, id);
      if (searchedName == null) {
        break missingId;
      }

      id = R.id.searchedUserPFP;
      CircleImageView searchedUserPFP = ViewBindings.findChildViewById(rootView, id);
      if (searchedUserPFP == null) {
        break missingId;
      }

      id = R.id.searchedUsername;
      TextView searchedUsername = ViewBindings.findChildViewById(rootView, id);
      if (searchedUsername == null) {
        break missingId;
      }

      id = R.id.userToolbar;
      Toolbar userToolbar = ViewBindings.findChildViewById(rootView, id);
      if (userToolbar == null) {
        break missingId;
      }

      return new SearchedUserBinding((ConstraintLayout) rootView, dislike, divider2, divider3,
          interests, like, searchedAge, searchedName, searchedUserPFP, searchedUsername,
          userToolbar);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
